DROP TABLE IF EXISTS dbo.D_DATE;
CREATE TABLE D_DATE
(
	dt VARCHAR(10) PRIMARY KEY NOT NULL
)
DECLARE @DT as VARCHAR(10)
DECLARE @START as DATETIME
DECLARE @END as DATETIME
SET @START = CONVERT(DATETIME, '2017.01.01', 102)
SET @END = CONVERT(DATETIME, '2037.01.01', 102)
WHILE @START < @END
BEGIN
	INSERT INTO D_DATE VALUES (CONVERT(VARCHAR(10), @START, 120))
	SET @START = DATEADD(DAY, 1, @START)
END